### ISSUE TITLE
Back version (8.9.1)

### ISSUE THREAD

**Issue by jmeppley** [conda-forge/cherrypy-feedstock#30]
Is there a way to add a back version of cherrypy to conda-forge? I'm working on a package in bioconda where the original explicitly requires version 8.9.1, but only 8.0.0 made it into conda-forge and 9.0.0 seems to be significantly different.

**Comment by jmeppley** [comment]
According to @pelson in [conda-forge issue 472](https://github.com/conda-forge/conda-forge.github.io/issues/472), it might be possible to create a v8.9.1 branch to do this.

@pmlandwehr, I've created the 8.9.1 recipe in my [fork](https://github.com/jmeppley/cherrypy-feedstock/tree/v8.9.1) but I'm not sure what to do next. I don't see a way to create a pull request into a new branch.

**Comment by pelson** [comment]
Branches can be made by recipe maintainers (cc @conda-forge/cherrypy) at which point you could create a pull request.
To speed things along a little, I notice there is already a 7.1 branch. I'm not a maintainer of cheerypi-feedstock, so don't know its purpose, but I wouldn't be surprised if that were now obsolete and needed deleting. You could potentially just submit a PR against that branch as the branch's last action 😉

**Comment by pelson** [comment]
P.S. If you are comfortable submitting a PR to update the cherrypy recipe, you might also consider joining the cherrypy recipe maintainer's team to help with its upkeep. Would certainly be most welcome help 👍

**Comment by carlodri** [comment]
Is this still needed?

**Comment by carlodri** [comment]
@jmeppley if you still need this, feel free to ping here, closing for now.
